name: CI/CD Workflow

on: 
  push: 
    branches: ['*']
    tags: ['*']
  pull_request: 
    branches: ['*']
    tags: ['*']

permissions:
  packages: write
  contents: read
  attestations: write
  id-token: write
  pull-requests: write

jobs: 
  build_and_test:
    name: Build and test
    uses: ./.github/workflows/build-test.yml

  push_to_registries:
    name: Publish Dockerimage
    uses: ./.github/workflows/publish.yml
